---
abstract: 'a DateTime object with different math'
author:
  - 'Mark Dominus <mjd@plover.com>'
build_requires:
  Test::Fatal: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Moonpig
requires:
  Carp: 0
  DateTime: 0
  Scalar::Util: 0
  Sub::Install: 0
  base: 0
  namespace::autoclean: 0
  overload: 0
  strict: 0
  warnings: 0
version: 0.92
